// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "aht10.h"

static aht10_device_t dev;
static char sensor_buf[32] = {0};
static char sensor_buf1[32] = {0};/////////

void show_callback(struct lv_timer_t *param)
{
    float temperature = aht10_read_temperature(dev);
    float humidity = aht10_read_humidity(dev);
    rt_sprintf(sensor_buf, "%.2f°\n", temperature);
    lv_label_set_text(ui_Label1, sensor_buf);
    rt_sprintf(sensor_buf1, "%.2f%%\n", humidity);
    lv_label_set_text(ui_Label4, sensor_buf1);
}

void show_ui_event(lv_event_t * e)
{
    dev = aht10_init("i2c3");
    if (dev == RT_NULL)
    {
        rt_kprintf("The sensor initializes failure\n");
        return;
    }

    // Your code here
    lv_timer_t * timer = lv_timer_create(show_callback, 1000, NULL);
    lv_timer_enable(true);

}
