// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

static char sensor_buf[32] = {0};
static char sensor_buf1[32] = {0};/////////

extern rt_mq_t mq_hum;
extern rt_mq_t mq_tem;

void show_callback(struct lv_timer_t *param)
{
    float brightness, humidity, temperature;

    rt_mq_recv(mq_hum, &humidity, sizeof(humidity), RT_WAITING_NO);
    rt_mq_recv(mq_tem, &temperature, sizeof(temperature), RT_WAITING_NO);

    rt_sprintf(sensor_buf, "%.2f°\n", temperature);
    lv_label_set_text(ui_Label1, sensor_buf);
    rt_sprintf(sensor_buf1, "%.2f%%\n", humidity);
    lv_label_set_text(ui_Label4, sensor_buf1);
}

void show_ui_event(lv_event_t * e)
{
    // Your code here
    lv_timer_t * timer = lv_timer_create(show_callback, 1000, NULL);
    lv_timer_enable(true);

}
